### ISSUE TITLE
how l can use this?

### ISSUE THREAD

**Issue by blacksdown** [TheCreeperCow/SCPSL-Donator-Tag#3]

**Comment by PatPeter** [comment]
New config:
Update DonorTag to Smod2 3.1.3 and streamline the configuration of DonorTag to a single configuration setting. Used as follows:

donor_tags: "78912345678901234;Donator 1;silver,78912345678901235;Donator 2;pink"

**Comment by blacksdown** [comment]
> 新配置：
> 将DonorTag更新为Smod2 3.1.3，并将DonorTag的配置简化为单个配置设置。使用如下：
> 
> donor_tags：“78912345678901234; Donator 1; silver，78912345678901235; Donator 2; pink”

Thank you! I also want to know how many colors can be displayed in the game.

**Comment by blacksdown** [comment]
Should l put this command in config_gameplay.txt ?

**Comment by PatPeter** [comment]
Yes, it goes in your `config_gameplay.txt`. Here are the colors currently available...

```php
< 12. As a server owner, what colours can I use for role tags? >

Colour    |    Restricted
============================
> gold                #
> teal                #
> blue                #
> purple              #
> light_red           #
pink
red
default
brown
silver
light_green
crimson
cyan
aqua
deep_pink
tomato
yellow
magenta
blue_green
> silver_blue         #
orange
> police_blue         # 
lime
green
emerald
carmine
nickel
mint
army_green
```

**Comment by PatPeter** [comment]
Closing this issue as configuration donor tags will soon be deprecated.
